#!/usr/bin/env python

"""confgit
Usage:
  confgit add <filename>
  confgit update <filename>
  confgit push
  confgit list
  confgit (-h | --help)
  confgit --version
"""
import os
import yaml
from docopt import docopt
from repo import Repository


if __name__ == '__main__':
    arguments = docopt(__doc__, version='confgit 1.0')
  
    config = yaml.load(file("{}/.confgit/config.yaml".format(os.environ['HOME'])))
    repo = Repository(config['backup_repo_dir'])

    if arguments['add']:
        repo.add(arguments['<filename>'])
    elif arguments['list']:
        repo.list()
    elif arguments['update']:
        repo.update(arguments['<filename>'])
    elif arguments['push']:
        repo.push()
